#!/usr/bin/env python3
"""Build the machine-readable research graph (graph.json) and per-problem
STATUS.md dashboards from attempt metadata.

Usage:
    python scripts/build_graph.py [--check]

--check: build in memory only, write nothing (used by CI on PRs).
"""

import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PROBLEMS_DIR = ROOT / "problems"

STATUS_ORDER = [
    "formalized",
    "expert-reviewed",
    "reproduced",
    "candidate",
    "exploration",
    "refuted",
    "withdrawn",
]

STATUS_EMOJI = {
    "exploration": "🔬",
    "candidate": "🟡",
    "reproduced": "🔁",
    "expert-reviewed": "✅",
    "formalized": "🏛️",
    "refuted": "❌",
    "withdrawn": "🚫",
}


class StrDateLoader(yaml.SafeLoader):
    pass


StrDateLoader.add_constructor(
    "tag:yaml.org,2002:timestamp",
    lambda loader, node: loader.construct_scalar(node),
)


def load_yaml(path: Path):
    with path.open() as fh:
        return yaml.load(fh, Loader=StrDateLoader)


def collect():
    problems = []
    for problem_dir in sorted(p for p in PROBLEMS_DIR.iterdir() if p.is_dir()):
        if problem_dir.name.startswith("_"):
            continue
        meta = load_yaml(problem_dir / "problem.yaml")
        attempts = []
        attempts_dir = problem_dir / "attempts"
        if attempts_dir.is_dir():
            for attempt_dir in sorted(p for p in attempts_dir.iterdir() if p.is_dir()):
                a = load_yaml(attempt_dir / "attempt.yaml")
                attempts.append(a)
        problems.append({"meta": meta, "attempts": attempts, "dir": problem_dir})
    return problems


def build_graph_json(problems):
    return {
        "generated_by": "scripts/build_graph.py",
        "problems": [
            {
                "id": p["meta"]["id"],
                "title": p["meta"]["title"],
                "area": p["meta"].get("area"),
                "status": p["meta"]["status"],
                "tags": p["meta"].get("tags", []),
                "attempt_count": len(p["attempts"]),
            }
            for p in problems
        ],
        "attempts": [
            {
                "id": a["id"],
                "problem": p["meta"]["id"],
                "type": a["type"],
                "status": a["claim"]["status"],
                "parents": a.get("parents", []),
                "refutes": a.get("refutes"),
                "context": a.get("context"),
                "contributor_kind": a["contributor"]["kind"],
                "model": a["contributor"].get("model"),
                "claim": a["claim"]["summary"],
                "created": a.get("created"),
            }
            for p in problems
            for a in p["attempts"]
        ],
    }


def mermaid_id(attempt_id: str) -> str:
    return "a_" + attempt_id.replace("-", "_")


def build_status_md(problem) -> str:
    meta, attempts = problem["meta"], problem["attempts"]
    lines = [
        f"# Status — {meta['title']}",
        "",
        "_Auto-generated by `scripts/build_graph.py`. Do not edit by hand._",
        "",
    ]

    by_status: dict[str, int] = {}
    for a in attempts:
        by_status[a["claim"]["status"]] = by_status.get(a["claim"]["status"], 0) + 1
    dead_ends = sum(1 for a in attempts if a["type"] == "dead-end")
    refutations = sum(1 for a in attempts if a["type"] == "refutation")

    summary = [f"**Problem status:** `{meta['status']}`", f"**Attempts:** {len(attempts)}"]
    for s in STATUS_ORDER:
        if by_status.get(s):
            summary.append(f"{STATUS_EMOJI[s]} {s}: {by_status[s]}")
    summary.append(f"dead ends recorded: {dead_ends}")
    summary.append(f"refutations: {refutations}")
    lines.append(" · ".join(summary))
    lines.append("")

    if attempts:
        lines += ["## Attempt graph", "", "```mermaid", "graph TD"]
        for a in attempts:
            label = f"{a['id']}<br/>{a['type']} · {a['claim']['status']}"
            lines.append(f'    {mermaid_id(a["id"])}["{label}"]')
        for a in attempts:
            for parent in a.get("parents", []):
                lines.append(f"    {mermaid_id(parent)} --> {mermaid_id(a['id'])}")
            if a.get("refutes"):
                lines.append(f"    {mermaid_id(a['id'])} -. refutes .-> {mermaid_id(a['refutes'])}")
        lines += ["```", ""]

        lines += [
            "## Attempts",
            "",
            "| id | type | status | contributor | claim |",
            "|---|---|---|---|---|",
        ]
        for a in attempts:
            who = a["contributor"]["kind"]
            if a["contributor"].get("model"):
                who += f" ({a['contributor']['model']})"
            claim = a["claim"]["summary"].replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| [{a['id']}](attempts/{a['id']}/WRITEUP.md) | {a['type']} | "
                f"{STATUS_EMOJI[a['claim']['status']]} {a['claim']['status']} | {who} | {claim} |"
            )
        lines.append("")
    else:
        lines += ["_No attempts yet. Be the first — see [AGENTS.md](../../AGENTS.md)._", ""]

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="build only; write nothing")
    args = parser.parse_args()

    problems = collect()
    graph = build_graph_json(problems)
    status_files = {p["dir"] / "STATUS.md": build_status_md(p) for p in problems}

    if args.check:
        print(f"OK (dry run) — graph: {len(graph['problems'])} problems, {len(graph['attempts'])} attempts")
        return 0

    (ROOT / "graph.json").write_text(json.dumps(graph, indent=2) + "\n", encoding="utf-8")
    for path, content in status_files.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    print(f"wrote graph.json ({len(graph['attempts'])} attempts across {len(graph['problems'])} problems)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
